In [1]:
import numpy as np
import warp as wp

# Explicitly initializing Warp is not necessary but
# we do it here to ensure everything is good to go.
wp.init()

if not wp.get_cuda_device_count():
    print(
        "Some snippets in this notebook assume the presence of "
        "a CUDA-compatible device and won't run correctly without one."
    )
     

Warp 1.11.0 initialized:
   CUDA Toolkit 12.9, Driver 13.0
   Devices:
     "cpu"      : "x86_64"
     "cuda:0"   : "NVIDIA GeForce RTX 4060 Laptop GPU" (8 GiB, sm_89, mempool enabled)
   Kernel cache:
     /home/thanh/.cache/warp/1.11.0


In [2]:
# Operation between 32-bit integers.
print("\nx:")
x = 123 + 234
print(x)

# Operation between 32-bit floating-points.
print("\ny:")
y = 1.2 + 2.3
print(y)

# Operation between 8-bit integers.
print("\nz:")
z = wp.int8(1) + wp.int8(2)
print(z)

# Invalid operation, both integer types must match.
print("\nw:")
try:
    w = wp.int8(1) + wp.int16(2)
    print(w)
except Exception:
    print("invalid operation")
     


x:
357

y:
3.5

z:
3

w:
invalid operation


In [3]:
# Rotate and scale a position vector.
print("\nnew_pos:")
pos = wp.vec3(1.0, 2.0, 3.0)
rot = wp.mat33(1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0)
scale = 0.5
new_pos = (pos * rot) * scale
print(new_pos)


new_pos:
[15.0, 18.0, 21.0]


In [4]:
# Create a 5D vector of 32-bit floating-points.
print("\nv:")
vec5f = wp.types.vector(length=5, dtype=wp.float32)
v = vec5f(1.0, 2.0, 3.0, 4.0, 5.0)
print(v)

# Create a 2x3 matrix of 32-bit floating-points.
print("\nm:")
mat23f = wp.types.matrix(shape=(2, 3), dtype=wp.float32)
m = mat23f(1.0, 2.0, 3.0, 4.0, 5.0, 6.0)
print(m)
     


v:
[1.0, 2.0, 3.0, 4.0, 5.0]

m:
[[1.0, 2.0, 3.0],
 [4.0, 5.0, 6.0]]


In [5]:
# Create a 1D array of integers.
print("\narr_int:")
arr_int = wp.array((1, 2, 3), dtype=int)
print(f"dtype={arr_int.dtype}, shape={arr_int.shape}")
print(arr_int)

# Create a 1D array of vectors.
print("\narr_vec:")
arr_vec = wp.array(((1, 2, 3), (4, 5, 6)), dtype=wp.vec3)
print(f"dtype={arr_vec.dtype}, shape={arr_vec.shape}")
print(arr_vec)

# Create a 2D array of floating-points.
print("\narr_2d:")
arr_2d = wp.array(((1, 2, 3), (4, 5, 6)), dtype=float)
print(f"dtype={arr_2d.dtype}, shape={arr_2d.shape}")
print(arr_2d)


arr_int:
dtype=<class 'warp._src.types.int32'>, shape=(3,)
[1 2 3]

arr_vec:
dtype=<class 'warp._src.types.vec3f'>, shape=(2,)
[[1. 2. 3.]
 [4. 5. 6.]]

arr_2d:
dtype=<class 'warp._src.types.float32'>, shape=(2, 3)
[[1. 2. 3.]
 [4. 5. 6.]]


In [6]:
# Create an array filled with zeros.
print("\narr_zeros:")
arr_zeros = wp.zeros(3)
print(f"dtype={arr_zeros.dtype}, shape={arr_zeros.shape}")
print(arr_zeros)

# Create an array filled with ones.
print("\narr_ones:")
arr_ones = wp.ones(3)
print(f"dtype={arr_ones.dtype}, shape={arr_ones.shape}")
print(arr_ones)

# Create an uninitialized array.
print("\narr_empty:")
arr_empty = wp.empty(3)
print(f"dtype={arr_empty.dtype}, shape={arr_empty.shape}")
print(arr_empty)

# Create an array filled with a custom value.
print("\narr_custom:")
arr_custom = wp.full(3, 123)
print(f"dtype={arr_custom.dtype}, shape={arr_custom.shape}")
print(arr_custom)


arr_zeros:
dtype=<class 'warp._src.types.float32'>, shape=(3,)
[0. 0. 0.]

arr_ones:
dtype=<class 'warp._src.types.float32'>, shape=(3,)
[1. 1. 1.]

arr_empty:
dtype=<class 'warp._src.types.float32'>, shape=(3,)
[0. 0. 0.]

arr_custom:
dtype=<class 'warp._src.types.int32'>, shape=(3,)
[123 123 123]


In [7]:
# Initialize an array from NumPy.
print("\narr_from_np:")
rng = np.random.default_rng(seed=123)
arr_np = rng.standard_normal((4, 2)).astype(np.float16)
arr_from_np = wp.from_numpy(arr_np)
print(f"dtype={arr_from_np.dtype}, {arr_from_np.shape}")
print(arr_from_np)
     


arr_from_np:
dtype=<class 'warp._src.types.vector.<locals>.vec_t'>, (4,)
[[-0.9893 -0.3677]
 [ 1.288   0.194 ]
 [ 0.9204  0.577 ]
 [-0.636   0.542 ]]


In [8]:

# Create a new data type made of 2 fields.
@wp.struct
class Obstacle:
    pos: wp.vec3
    radius: float


# Create a first instance.
print("\no1:")
o1 = Obstacle()
o1.pos = wp.vec3(1.0, 2.0, 3.0)
o1.radius = 0.75
print(o1)

# Create a second instance.
print("\no2:")
o2 = Obstacle()
o2.pos = wp.vec3(2.0, 3.0, 4.0)
o2.radius = 0.5
print(o2)

# Create an array with these instances.
print("\narr_struct:")
arr_struct = wp.array((o1, o2), dtype=Obstacle)
print(f"dtype={arr_struct.dtype}, shape={arr_struct.shape}")
print(arr_struct)


o1:
Obstacle(
	pos=[1.0, 2.0, 3.0],
	radius=0.75,
)

o2:
Obstacle(
	pos=[2.0, 3.0, 4.0],
	radius=0.5,
)

arr_struct:
dtype=<warp._src.codegen.Struct object at 0x70410a526ba0>, shape=(2,)
[([1., 2., 3.], 0.75) ([2., 3., 4.], 0.5 )]
